In [3]:
from sklearn. linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier 
import numpy as np 
from sklearn.datasets import load_digits

digits = load_digits ()

In [18]:
from sklearn. model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [19]:
Ir = LogisticRegression()
Ir.fit (X_train, y_train)
Ir.score (X_test, y_test)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [20]:
svm = SVC()
svm.fit (X_train, y_train) 
svm.score (X_test, y_test)

0.9740740740740741

In [21]:
rf = RandomForestClassifier (n_estimators=40)
rf.fit(X_train, y_train) 
rf.score(X_test, y_test)

0.9574074074074074

In [25]:
from sklearn.model_selection import KFold
kf = KFold (n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [27]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,91]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [29]:
def get_score (model, X_train, X_test, y_train, y_test):
    model.fit (X_train, y_train)
    return model.score (X_test, y_test)

In [35]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [31]:
get_score(LogisticRegression(),X_train,X_test,y_train, y_test)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629